services:
  db:
    image: postgres:15-alpine
    container_name: hypo_health_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hypo_network
    #healthcheck:
      #test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      #interval: 5s
      #timeout: 5s
      #retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hypo_health_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - hypo_network
    #depends_on:
      #db:
        #condition: service_healthy

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: hypo_health_mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./iot/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - hypo_network 

networks:
  hypo_network: 
    driver: bridge

volumes:
  pgdata: